# -*- coding: utf-8 -*-
"""ICA3_KatiJohnson.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PqP0IJzyJI_NxwPerjEshmi3yCGOtVUU

Please read the first 1000 lines from the lego_setsHB.csv in the DATA folder and split each line by using comma. (You may have to make a copy of the DATA folder to your own drive to be able to read from there. You can create a short cut to your drive as shown at the beginning of the Lecture 5)

As you do go through each line populate two dictionaries, Price and Difficulty, which use product id as the key and price and review difficulty as values, respectively.
"""

def createDict(filename):
  counter = 0
  price = {}
  difficulty = {}
  with open(filename, 'r') as fl:
    next(fl)
    for line in fl:
      tokens = line.split(',')
      price[tokens[4]] = tokens[0]
      difficulty[tokens[4]] = tokens[5]
      counter+=1
      if counter == 1000:
        break
  return price, difficulty

def printDicts(price, difficulty):
  for key, value in price.items():
    print(key, value, difficulty[key])

def main():
  filename = '/content/drive/MyDrive/CSC302/DATA/lego_setsHB.csv'
  price, difficulty = createDict(filename)
  printDicts(price, difficulty)

main()